var data = [[[['TOPOR', 'Ginette', 'f', 'Paris 11, Paris, France', '1944'], ['SIMON', 'Claude, Maurice', 'g', 'Hayange, Moselle, France', '1934'], ['SZLADOWER', 'Mendel', 'g', 'Warszawa, Masovia, Pologne', '1927']],
			[],
			[],
			[['BAËR', 'Yvette, Suzanne', 'f', 'Metz, Moselle, France', '1938'], ['WAJNTROB', 'Josette', 'f', 'Paris 13, Paris, France', '1932']],
			[['REZNIKOW', 'Gilbert', 'g', 'Paris 10, Paris, France', '1943']],
			[['MAMAN', 'Lili', 'f', 'Paris 10, Paris, France', '1935'], ['DRAZNIN', 'Mojzesz', 'g', 'Hrodna, Hrodna [Grodno], Biélorussie', '1927']],
			[],
			[['METZGER', 'Monique, Claude, Hélène', 'f', 'Saverne, Bas-Rhin, France', '1939'], ['WAKS', 'Rosa', 'f', 'Paris 20, Paris, France', '1934']],
			[],
			[['HERSZKOWICZ', 'Simone', 'f', 'Romilly-sur-Seine, Aube, France', '1943']],
			[],
			[],
			[['AKIBA', 'Serge, Salomon', 'g', 'Boulogne-Billancourt, Hauts-de-Seine, France', '1927']],
			[['WAJNCWAJG', 'Paulette', 'f', 'Paris 1, Paris, France', '1944'], ['SZMIDT', 'Simon', 'g', 'Paris 12, Paris, France', '1941']],
			[],
			[['BERLINER', 'Régine, Suzanne', 'f', 'Paris 20, Paris, France', '1943']],
			[['ZELIDZOW', 'Claude, Michel', 'g', 'Paris 10, Paris, France', '1930']],
			[['SZWARCBAUM', 'Madeleine', 'f', 'Paris 10, Paris, France', '1943']],
			[['METZLER', 'Bertrand, René', 'g', 'Jarnac, Charente, France', '1941']],
			[],
			[['BERG', 'Jean-Pierre', 'g', 'Boulogne-sur-Mer, Pas-de-Calais, France', '1934']],
			[['GRYNER', 'Danielle, Betty', 'f', 'Paris 20, Paris, France', '1944'], ['GUNTZBURGER', 'Andrée, Rachel', 'f', 'Strasbourg, Bas-Rhin, France', '1931'], ['MARX', 'Claudine, Caroline', 'f', 'Sierck-les-Bains, Moselle, France', '1937'], ['BAER', 'Simon', 'g', 'Metz, Moselle, France', '1932']],
			[['KAHN', 'Yvette', 'f', 'Chaumont, Haute-Marne, France', '1928']],
			[],
			[['KULBERG', 'Danièle, Rachelle', 'f', 'Paris 12, Paris, France', '1940']],
			[['ABOUDY', 'Paulette, Marcelle', 'f', 'Marseille, Bouches-du-Rhône, France', '1930']],
			[],
			[],
			[['ROGOZYK', 'Victor', 'g', 'Paris, Paris, France', '1934']],
			[['WAJNEROWICZ', 'Claudine', 'f', 'Paris 18, Paris, France', '1943']],
			[]],
			[[['DAVY', 'Roger', 'g', "Saint-Brieuc, Côtes-d'Armor, France", '1941']],
			[['ROZENBAUM - FEIFER', 'Gabriel', 'g', 'Paris 3, Paris, France', '1942']],
			[['MONCARZ', 'David, Victor', 'g', 'Paris 12, Paris, France', '1933']],
			[['PELCMAN', 'Pauline', 'f', 'Paris 12, Paris, France', '1941'], ['BLOCH', 'Jean-Pierre', 'g', 'Paris 17, Paris, France', '1931'], ['FRIEDMAN', 'Adolphe, Nathan', 'g', 'Paris 12, Paris, France', '1931']],
			[],
			[],
			[['KAPLAN', 'Frida', 'f', 'Metz, Moselle, France', '1930']],
			[['HUBERFELD', 'Pierre', 'g', 'Bar-sur-Aube, Aube, France', '1938'], ['WAJNCWAJG', 'Victor', 'g', 'Paris 12, Paris, France', '1942']],
			[],
			[['LANDAU', 'Hudesa, Adèle', 'f', 'Łowicz, Łódź, Pologne', '1929'], ['PRZEROWSKI', 'Ginette', 'f', 'Metz, Moselle, France', '1932']],
			[['KALMANOWICZ', 'Rachel', 'f', 'Paris 14, Paris, France', '1933'], ['FUCHS', 'Francis', 'g', 'Saint-Avold, Moselle, France', '1939']],
			[],
			[['WALDKIRCH', 'Simonne', 'f', 'Sedan, Ardennes, France', '1928'], ['KAPLAN', 'David', 'g', 'Metz, Moselle, France', '1932']],
			[['SEGAL', 'Raymonde', 'f', 'Paris 18, Paris, France', '1935'], ['SZTULZAFT', 'Marcel', 'g', 'Paris 4, Paris, France', '1927']],
			[['BACRI', 'Lise, Joséphine', 'f', 'Paris 17, Paris, France', '1926'], ['CHOROSZEZ', 'Bernard', 'g', 'Paris 10, Paris, France', '1927']],
			[],
			[],
			[['METZLER', 'Germaine, Nelly', 'f', 'Sarreguemines, Moselle, France', '1930'], ['KAPLAN', 'Jacques', 'g', 'Metz, Moselle, France', '1926'], ['SZYPPER', 'Alfred', 'g', 'Paris 20, Paris, France', '1930']],
			[],
			[],
			[['BAER', 'Ginette, Caroline', 'f', 'Saint-Pierre-de-Juillers, Charente-Maritime, France', '1943'], ['BOKSENBAUM', 'Lucie, Léa', 'f', 'Paris 4, Paris, France', '1932'], ['PRZEROWSKI', 'Hilda', 'f', 'Metz, Moselle, France', '1929'], ['SABAH', 'Claire', 'f', 'La Roche-sur-Yon, Vendée, France', '1930']],
			[['MONCARZ', 'Hélène', 'f', 'Paris 12, Paris, France', '1940'], ['ROTSZTEIN', 'Samy', 'g', 'Bressuire, Deux-Sèvres, France', '1935']],
			[['LANDAU', 'Hélène', 'f', 'Paris 12, Paris, France', '1933']],
			[['PELCMAN', 'Simone', 'f', 'Paris 12, Paris, France', '1930'], ['MAMAN', 'Samy', 'g', 'Paris 12, Paris, France', '1942']],
			[],
			[['CANTKERT', 'Suzanne', 'f', 'Paris 12, Paris, France', '1935'], ['HANNAUX', 'Denyse, Fleurette', 'f', 'Freistroff, Moselle, France', '1933']],
			[],
			[['BING', 'Yolaine, Pauline, Yolande', 'f', 'Sierck-les-Bains, Moselle, France', '1931'], ['WAKS', 'Nathan, Bernard', 'g', 'Paris 20, Paris, France', '1940']],
			[],
			[],
			[]],
			[[['MASLIAH', 'Maurice', 'g', 'Paris 14, Paris, France', '1932']],
			[],
			[['EISENBERG', 'Françoise', 'f', 'Paris 12, Paris, France', '1932'], ['FEFER', 'Lejzer', 'g', 'Paris 4, Paris, France', '1941']],
			[['BERG', 'Huguette', 'f', 'Paris 17, Paris, France', '1931'], ['LASKOWSKI', 'Chaïm, Jacob', 'g', 'Paris 12, Paris, France', '1926']],
			[],
			[],
			[],
			[],
			[],
			[['CUCIUC', 'Alice', 'f', 'Paris 18, Paris, France', '1939']],
			[],
			[['MAKOWSKI', 'Élie', 'g', 'Strasbourg, Bas-Rhin, France', '1930'], ['MEISELS', 'Claude', 'g', 'Paris 10, Paris, France', '1931'], ['SZWARCBURG', 'Michel', 'g', 'Paris 12, Paris, France', '1933']],
			[['BOKSENBAUM', 'Jacqueline', 'f', 'Paris 20, Paris, France', '1943']],
			[],
			[],
			[],
			[],
			[],
			[['SZRAJEK', 'Robert', 'g', 'Paris 10, Paris, France', '1930']],
			[['ROJZNER', 'Freda', 'f', 'Paris 12, Paris, France', '1933'], ['SZTANKE', 'Marie, Denise', 'f', 'Paris 12, Paris, France', '1933']],
			[['BAER', 'Irène, Juliette', 'f', 'Fouras, Charente-Maritime, France', '1940'], ['KARP', 'Michel', 'g', 'Paris 12, Paris, France', '1943']],
			[['EHRLICH - GOLDFARB', 'Claudine', 'f', 'Paris 12, Paris, France', '1943'], ['SIMON', 'Rosine', 'f', 'Puttelange-aux-Lacs, Moselle, France', '1931']],
			[['PYTEL', 'Rosette, Berthe', 'f', 'Paris 6, Paris, France', '1942'], ['FRYDEL', 'Jacques', 'g', 'Metz, Moselle, France', '1934']],
			[['RINDLER', 'Charlotte', 'f', 'Metz, Moselle, France', '1927'], ['KELLER', 'Michel', 'g', 'Belfort, Territoire de Belfort, France', '1935']],
			[['GOLDZTEJN', 'Roger', 'g', 'Paris 12, Paris, France', '1931']],
			[],
			[['PASAMANIK', 'Fernand', 'g', 'Paris 12, Paris, France', '1939']],
			[['OSSJA', 'Salomon', 'g', 'Paris 10, Paris, France', '1942']],
			[],
			[],
			[['ZEMMOUR', 'Claudette, Monique, Gisèle', 'f', 'Paris 10, Paris, France', '1932']]],
			[[['SEGAL', 'Liliane, Dorothée', 'f', 'Paris 18, Paris, France', '1934'], ['ROZENBERG', 'Maurice', 'g', 'Paris 20, Paris, France', '1943']],
			[],
			[['BLASZKA', 'Léon', 'g', 'Paris 11, Paris, France', '1928']],
			[['HANAU', 'Margot', 'f', 'Dillingen, Saarland, Allemagne', '1926'], ['ADILA', 'Charles', 'g', 'Paris 10, Paris, France', '1928']],
			[['JACOB', 'Françoise, Gisèle', 'f', 'Thionville, Moselle, France', '1934']],
			[['MIZRAHI', 'Rachel, Ginette, Néama', 'f', 'Montluçon, Allier, France', '1930'], ['TYKOCZINSKI - SZTEINBERG', 'Victoria', 'f', 'Paris 12, Paris, France', '1941']],
			[],
			[['BAËR', 'Robert', 'g', 'Metz, Moselle, France', '1932']],
			[],
			[['BAËR', 'Anna', 'f', 'Metz, Moselle, France', '1929'], ['SIMON', 'Mélanie', 'f', 'Puttelange-aux-Lacs, Moselle, France', '1930']],
			[],
			[],
			[],
			[],
			[['ABRAMOWICZ', 'Rachel', 'f', 'Paris 12, Paris, France', '1928']],
			[['KUPERMAN', 'Joseph', 'g', "Saint-Jean-D'Angély, Charente-Maritime, France", '1940']],
			[['PASAMANIK', 'Salomon', 'g', 'Paris 12, Paris, France', '1931'], ['ROTSZTEIN', 'Léon', 'g', 'Paris 12, Paris, France', '1927']],
			[],
			[],
			[],
			[],
			[['BACRI', 'Nicole', 'f', 'Paris 17, Paris, France', '1930'], ['GRYNBERG', 'Thérèse', 'f', 'Paris 4, Paris, France', '1942']],
			[['METZLER', 'Suzanne, Denise', 'f', 'Sarreguemines, Moselle, France', '1939'], ['GLIOT', 'Robert', 'g', 'Metz, Moselle, France', '1930'], ['SLIWKA', 'Maurice', 'g', 'Paris 14, Paris, France', '1940']],
			[['ROTSZTEIN', 'Félix', 'g', 'Paris 12, Paris, France', '1933']],
			[],
			[['RYBAK', 'Joseph', 'g', 'Paris 4, Paris, France', '1941'], ['SALOMON', 'Jacques', 'g', 'Dun-sur-Meuse, Meuse, France', '1928']],
			[['JABLONSKI', 'André', 'g', 'Sarreguemines, Moselle, France', '1939']],
			[['PRZEROWSKI', 'Dora', 'f', 'Metz, Moselle, France', '1935']],
			[['HERRMANN', 'Simone', 'f', 'Chaumont, Haute-Marne, France', '1927']],
			[],
			[]],
			[[['BLOCH', 'Nicole, Rose, Elisabeth', 'f', 'Nice, Alpes-Maritimes, France', '1927'], ['BOLESLAWSKI', 'Estelle', 'f', 'Montélimar, Drôme, France', '1942'], ['NUSSBAUM', 'Édith', 'f', 'Forbach, Moselle, France', '1934']],
			[['KELLER', 'Sara', 'f', 'Przemyśl, Podkarpackie, Pologne', '1928'], ['LEVY', 'Denise', 'f', 'Étain, Meuse, France', '1934'], ['MAJZNER', 'Robert', 'g', 'Paris 4, Paris, France', '1932']],
			[['LAMBERT', 'Josette, Arlette', 'f', 'Hellimer, Moselle, France', '1931']],
			[['CANTKERT', 'Paul', 'g', 'Paris 12, Paris, France', '1933']],
			[['MAKOWSKI', 'Denise', 'f', 'Strasbourg, Bas-Rhin, France', '1931'], ['SIMON', 'Guillaume, Robert, Silvain', 'g', 'Puttelange-aux-Lacs, Moselle, France', '1929']],
			[['DORFMAN', 'Paulette', 'f', 'Chișinău, Chișinău, Moldavie', '1926'], ['MANCARZ', 'Hélène', 'f', 'Paris 12, Paris, France', '1936'], ['ZERDOUN', 'Josiane, Rébecca, Françoise', 'f', 'Guelma, Guelma, Algérie', '1934']],
			[['OSSJA', 'Mireille', 'f', 'Paris 12, Paris, France', '1940']],
			[],
			[['ZEHMOUR', 'Jacqueline', 'f', 'Champigny-sur-Marne, Val-de-Marne, France', '1939'], ['LEVY', 'Edmond', 'g', 'Étain, Meuse, France', '1929']],
			[],
			[],
			[['STRAUSS', 'Liliane', 'f', 'Obernai, Bas-Rhin, France', '1939'], ['FRIEDMAN', 'Michel', 'g', 'Paris 12, Paris, France', '1935']],
			[['SEIDEN', 'Élias', 'g', 'Metz, Moselle, France', '1926']],
			[],
			[],
			[['SCHAUL', 'Anja', 'f', 'Paris 14, Paris, France', '1937']],
			[['CHOROSZEZ', 'Fernande, Marie', 'f', 'Paris 10, Paris, France', '1942']],
			[],
			[],
			[],
			[],
			[],
			[['ABOULHAIR', 'Albert, Roger', 'g', 'Paris 12, Paris, France', '1934'], ['HILF', 'Boris, Guillaume', 'g', 'Paris 3, Paris, France', '1929'], ['JAKUBOWITZ', 'Isaac', 'g', 'Nancy, Meurthe-et-Moselle, France', '1927'], ['MILGRAM', 'Maurice', 'g', 'Paris 12, Paris, France', '1942']],
			[],
			[],
			[['HANNAUX', 'Arlette, Josette, Babette', 'f', 'Freistroff, Moselle, France', '1938'], ['LINDENBAUM', 'Blanche, Suzanne', 'f', 'Paris 4, Paris, France', '1934'], ['ZANGIER', 'Jeanine, Nicolle', 'f', 'Paris 4, Paris, France', '1934']],
			[],
			[],
			[['ARBISER', 'Sarah', 'f', 'Warszawa, Masovia, Pologne', '1929']],
			[],
			[]],
			[[['DREYFUS', 'Claude', 'f', 'Colmar, Haut-Rhin, France', '1928'], ['ZAKS', 'Claudette', 'f', 'Paris 14, Paris, France', '1938'], ['BLOCH', 'Claude, Jacques', 'g', 'Haguenau, Bas-Rhin, France', '1928']],
			[['JACOB', 'Jean, Moyse', 'g', 'Thionville, Moselle, France', '1937']],
			[['MONCARZ', 'Jacques', 'g', 'Paris 12, Paris, France', '1935']],
			[['SOMMER', 'Simone, Madeleine', 'f', 'Strasbourg, Bas-Rhin, France', '1937']],
			[],
			[],
			[['LAMBERT', 'Ginette', 'f', 'Strasbourg, Bas-Rhin, France', '1930']],
			[['SAMUEL', 'Claude, Salomon', 'g', 'Caen, Calvados, France', '1927']],
			[['HERSCHER', 'Odette, Eva', 'f', 'Paris 4, Paris, France', '1929']],
			[['LANDAU', 'Victor', 'g', 'Paris 4, Paris, France', '1943']],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[],
			[['PYTEL', 'Jacques, Bernard', 'g', 'Paris 14, Paris, France', '1937']],
			[['SILZ', 'Hilaire, Gérard', 'g', 'Nice, Alpes-Maritimes, France', '1930']],
			[['GUNTZBURGER', 'Paul, Aloyse', 'g', 'Mommenheim, Bas-Rhin, France', '1932']],
			[],
			[['DAVY', 'Joseph', 'g', "Saint-Brieuc, Côtes-d'Armor, France", '1937'], ['DAVY', 'Léon', 'g', "Saint-Brieuc, Côtes-d'Armor, France", '1937']],
			[],
			[['DALTROFF', 'Léon, Alfred', 'g', 'Metz, Moselle, France', '1926']],
			[],
			[['BAER', 'Éliane, Claire', 'f', 'Chaumont, Haute-Marne, France', '1931']],
			[['MEYER', 'Liliane, Françoise', 'f', 'Paris 16, Paris, France', '1930']],
			[]],
			[[['BLUMSTEIN', 'Amalia', 'f', 'Wien, Wien, Autriche', '1929']],
			[],
			[['SLOMILOVITCH', 'Jean', 'g', 'Paris 12, Paris, France', '1928']],
			[['HASMAN', 'Suzanne', 'f', 'Paris 12, Paris, France', '1942']],
			[],
			[['GITTMANN', 'Anny', 'f', 'Tours, Indre-et-Loire, France', '1940']],
			[['LEVY', 'Marcel', 'g', 'Archigny, Vienne, France', '1941'], ['SZTARKMAN', 'Pierre', 'g', 'Paris 12, Paris, France', '1940']],
			[['AHITOUF', 'Raphaël, Robert', 'g', 'Saint-Quentin, Aisne, France', '1932']],
			[],
			[],
			[['ARBISER', 'Nathan', 'g', 'Paris 12, Paris, France', '1932']],
			[],
			[],
			[['LANDAU', 'Daniel', 'g', 'Paris 4, Paris, France', '1936']],
			[['WAJSBORD', 'Ruchla, Necha', 'f', 'Radom, Masovia, Pologne', '1928'], ['MENDLEWITCH', 'Henri, Rubin', 'g', 'Paris 10, Paris, France', '1932']],
			[['SPIRA', 'Nelly', 'f', 'Colmar, Haut-Rhin, France', '1932']],
			[['WALDKIRCH', 'Germaine', 'f', 'Sedan, Ardennes, France', '1929']],
			[],
			[],
			[],
			[['BLOCH', 'Marguerite, Georgette', 'f', 'Guebwiller, Haut-Rhin, France', '1938'], ['KLODAWSKI', 'Simon', 'g', 'Reims, Marne, France', '1938']],
			[],
			[],
			[['PYTEL', 'Irène, Denise', 'f', 'Paris 14, Paris, France', '1939']],
			[],
			[['HERSCHER', 'Cécile', 'f', 'Roubaix, Nord, France', '1927'], ['LIBERMANN', 'Frederic', 'g', 'Paris 10, Paris, France', '1934'], ['SIODLOWICZ', 'Armand', 'g', 'Paris, Paris, France', '1932']],
			[],
			[],
			[],
			[],
			[['SLIWKA', 'Françoise', 'f', 'Paris 14, Paris, France', '1938']]],
			[[],
			[],
			[],
			[['LINDENBAUM', 'Madeleine', 'f', 'Paris 4, Paris, France', '1936'], ['SZNAJDERMAN', 'Marguerite', 'f', 'Paris 12, Paris, France', '1943'], ['RYBAK', 'Raim, Jacques', 'g', 'Paris 4, Paris, France', '1932']],
			[['ROZENBAUM', 'Jeannette', 'f', 'Paris 12, Paris, France', '1937'], ['AKRICHE', 'Claude, Yves, Philémon', 'g', 'Le Bourg sous la Roche, La Roche-sur-Yon, Vendée, France', '1927']],
			[['BAËR', 'Berthe', 'f', 'Metz, Moselle, France', '1936']],
			[],
			[],
			[['WORMSER', 'Simone, Jane', 'f', 'Paris 9, Paris, France', '1926']],
			[['SPIEGEL', 'Ida', 'f', 'Berlin, Berlin, Allemagne', '1927'], ['WAJNTROB', 'Denise', 'f', 'Paris 13, Paris, France', '1935'], ['PICARD', 'Francis, Gérard', 'g', 'Mulhouse, Haut-Rhin, France', '1932']],
			[['SABAH', 'Louise', 'f', 'La Roche-sur-Yon, Vendée, France', '1931']],
			[],
			[],
			[['ZERDOUN', 'Yves, Jean, Moïse', 'g', 'Guelma, Guelma, Algérie', '1935']],
			[['KALMANOWICZ', 'Berthe, Joséphine', 'f', 'Paris 10, Paris, France', '1934'], ['ZERDOUN', 'Raymond, André', 'g', 'Rochefort, Charente-Maritime, France', '1938']],
			[],
			[],
			[],
			[['LEVY', 'André', 'g', 'Bordeaux, Gironde, France', '1928']],
			[],
			[],
			[['GRYNBERG', 'Jacob', 'g', 'Paris 4, Paris, France', '1937']],
			[['WALDKIRCH', 'Jacques, Jaak', 'g', 'Sedan, Ardennes, France', '1935']],
			[],
			[],
			[['BASSAN', 'Michel, Maurice, Michoulam', 'g', "Saint-Brieuc, Côtes-d'Armor, France", '1937']],
			[],
			[],
			[['STRAUSS', 'Jeannette, Jeanne', 'f', 'Metz, Moselle, France', '1939']],
			[],
			[]],
			[[],
			[],
			[['WAJNSZTEIN', 'Fanny', 'f', 'Paris 19, Paris, France', '1941']],
			[],
			[['ZORGEN', 'Marie', 'f', 'Paris 14, Paris, France', '1927'], ['MIZRAHI', 'Lucien, Jacky', 'g', 'Montluçon, Allier, France', '1934']],
			[],
			[],
			[['SIMON', 'René, Joseph', 'g', 'Angoulême, Charente, France', '1940']],
			[['BAUM', 'Yvette', 'f', 'Haguenau, Bas-Rhin, France', '1926'], ['STUMPLER', 'Leo', 'g', 'Wien, Wien, Autriche', '1926']],
			[],
			[['FRYDEL', 'Françoise | Francine', 'f', 'Herserange, Meurthe-et-Moselle, France', '1928'], ['LOEW', 'Anne', 'f', 'Paris, Paris, France', '1938']],
			[['LANDAU', 'Suzanne', 'f', 'Paris 4, Paris, France', '1931']],
			[['FIDLER', 'Albertine, Rachel', 'f', 'Reims, Marne, France', '1926']],
			[],
			[],
			[],
			[['ROSEN', 'Colette', 'f', 'Saint-Dizier, Haute-Marne, France', '1931'], ['BERLINERBLAU', 'Élie', 'g', 'Paris 19, Paris, France', '1943'], ['IKKA', 'Jojne | Jean', 'g', 'Brzeziny, Łódź, Pologne', '1927']],
			[['BERNAT', 'Chana', 'f', 'Kałuszyn, Masovia, Pologne', '1928']],
			[['ARON', 'Jean-Jacques', 'g', 'Rosheim, Bas-Rhin, France', '1931'], ['SIMON', 'Robert', 'g', 'Sarralbe, Moselle, France', '1938'], ['SZNAJDERMAN', 'Henri', 'g', 'Paris 19, Paris, France', '1941']],
			[],
			[['KAHN', 'Robert', 'g', 'Völklingen, Saarland, Allemagne', '1930']],
			[['ROSENBERG', 'Suzanne', 'f', 'Annecy, Haute-Savoie, France', '1931']],
			[],
			[],
			[['BAËR', 'Hélène', 'f', 'Metz, Moselle, France', '1934'], ['ZAKS', 'Éliane', 'f', 'Paris 4, Paris, France', '1930']],
			[['ANGEL', 'Renée, Françoise', 'f', 'Saintes, Charente-Maritime, France', '1929']],
			[['LANDAU', 'Salomon', 'g', 'Paris 4, Paris, France', '1934']],
			[],
			[],
			[],
			[]],
			[[['BLOCH', 'Arlette', 'f', 'Mertzwiller, Bas-Rhin, France', '1930'], ['BLOCH', 'Liliane, Rosalie', 'f', 'Mertzwiller, Bas-Rhin, France', '1930'], ['RUDOLF', 'Josephine', 'f', 'Paris 10, Paris, France', '1942']],
			[],
			[],
			[],
			[['SIMON', 'Fernand', 'g', 'Cognac, Charente, France', '1939']],
			[],
			[['DORFMAN', 'Betty', 'f', 'Chișinău, Chișinău, Moldavie', '1927'], ['FRIEDMANN', 'Inès, Béatrix', 'f', 'Marseille, Bouches-du-Rhône, France', '1941']],
			[['GUINDINE', 'René', 'g', 'Suresnes, Hauts-de-Seine, France', '1927']],
			[['LIBERMANN', 'Pauline', 'f', 'Paris 12, Paris, France', '1938']],
			[['WAKS', 'Gabrielle', 'f', 'Paris 14, Paris, France', '1935']],
			[['PELCMAN', 'Maurice', 'g', 'Paris 12, Paris, France', '1934']],
			[['SOKOLOWSKI', 'Denise', 'f', 'Paris 12, Paris, France', '1932'], ['ARON', 'Guy', 'g', 'Rosheim, Bas-Rhin, France', '1938']],
			[],
			[['CANTKERT', 'Ita, Laja, Ida', 'f', 'Paris 12, Paris, France', '1927'], ['JAKUBOWSKI', 'Jean-Claude', 'g', 'Paris 20, Paris, France', '1942']],
			[],
			[],
			[['ACHACH', 'Yvette', 'f', 'Oran, Oran, Algérie', '1927']],
			[['SOKOLOWSKI', 'Rachel, Danielle', 'f', 'La Flèche, Sarthe, France', '1942']],
			[['CUKIER', 'Anna', 'f', 'Paris 18, Paris, France', '1940']],
			[],
			[],
			[],
			[['LAKSMAN', 'Simon', 'g', 'Paris 18, Paris, France', '1941'], ['MAKOWSKI', 'Gilbert', 'g', 'Bourbonne-les-Bains, Haute-Marne, France', '1940']],
			[['LEVI', 'Hélène, Georgette', 'f', 'Paris 12, Paris, France', '1927']],
			[['WAJNSZTEIN', 'Henry', 'g', 'Paris 19, Paris, France', '1934'], ['ZAKS', 'Daniel, Robert', 'g', 'Paris 4, Paris, France', '1934']],
			[['BING', 'Éliane, Hortense', 'f', 'Sierck-les-Bains, Moselle, France', '1928'], ['CANTKERT', 'Frida', 'f', 'Paris 12, Paris, France', '1939']],
			[['ROZENBERG', 'Bella', 'f', 'Paris, Paris, France', '1942'], ['ABOULHAIR', 'Edmond, Isidore', 'g', 'Paris 12, Paris, France', '1937'], ['TORRES', 'Albert', 'g', 'Paris 12, Paris, France', '1930']],
			[],
			[['WEIL', 'Jeannine, Julie', 'f', 'Strasbourg, Bas-Rhin, France', '1926'], ['DORN', 'Joseph, David', 'g', 'Metz, Moselle, France', '1926'], ['SZYPPER', 'Jean, Charles', 'g', 'Paris 12, Paris, France', '1941']],
			[],
			[]],
			[[],
			[],
			[['MILECKI', 'Marcel, Élie', 'g', 'Paris 19, Paris, France', '1939']],
			[],
			[],
			[['CUKIER', 'Esther, Malka', 'f', 'Paris 10, Paris, France', '1938']],
			[],
			[],
			[],
			[],
			[],
			[['ZAOUI', 'Estelle', 'f', 'Paris 18, Paris, France', '1940'], ['WAKS', 'Henri', 'g', 'Paris 20, Paris, France', '1932']],
			[],
			[['BLETTERMANN', 'Mozes', 'g', 'Antwerpen, Antwerpen, Belgique', '1936']],
			[],
			[['SZMIDT', 'Félix', 'g', 'Paris 20, Paris, France', '1926']],
			[['SEGAL', 'Gabriel', 'g', 'Paris 18, Paris, France', '1930']],
			[],
			[['FENSTERSZAB', 'Ida', 'f', 'Paris 12, Paris, France', '1929'], ['SZWARC', 'Françoise', 'f', 'Marseille, Bouches-du-Rhône, France', '1941']],
			[['ABOUDY', 'Suzanne, Fortunée', 'f', 'Marseille, Bouches-du-Rhône, France', '1927']],
			[],
			[['BAER', 'Nicole, Paule, Caroline, France', 'f', 'Chaumont, Haute-Marne, France', '1937'], ['MANCARZ', 'Suzanne', 'f', 'Paris 12, Paris, France', '1932']],
			[['MAMAN', 'Anna', 'f', 'Paris 18, Paris, France', '1936']],
			[['MEITLIS | ZAKS', 'Adam', 'g', 'Kraków, Małopolska, Pologne', '1926']],
			[['ROZENBERG', 'Évelyne', 'f', 'Paris 4, Paris, France', '1933']],
			[],
			[],
			[],
			[],
			[['BADER', 'Françoise', 'f', 'Charleville-Mézières, Ardennes, France', '1935'], ['KAHN', 'Odette', 'f', 'Völklingen, Saarland, Allemagne', '1927']],
			[]],
			[[['BERNAT', 'Renée, Rebeka', 'f', 'Kałuszyn, Masovia, Pologne', '1930'], ['METZLER', 'Carmen, Yvonne, Sophie', 'f', 'Sarreguemines, Moselle, France', '1928']],
			[],
			[['SZABASON', 'Elena', 'f', 'Buenos Aires, Buenos Aires, Argentine', '1927'], ['DAVY', 'Maurice', 'g', 'Paris 12, Paris, France', '1931']],
			[['WAKS', 'Jacques', 'g', 'Paris 20, Paris, France', '1937']],
			[],
			[],
			[['STEINLAUF', 'Germaine', 'f', 'Nice, Alpes-Maritimes, France', '1932']],
			[],
			[['ECKHAJZER', 'Chaya', 'f', 'Warszawa, Masovia, Pologne', '1927']],
			[],
			[['FEFER', 'Paulette', 'f', 'Paris 4, Paris, France', '1943'], ['GOLDSZTEJN', 'Rose', 'f', 'Paris 12, Paris, France', '1942'], ['MAMAN', 'Simha, Mauricette', 'f', 'Paris 12, Paris, France', '1940'], ['MIZRAHI', 'Jean-Claude', 'g', 'La Rochelle, Charente-Maritime, France', '1941']],
			[['BAER', 'Claude, Marie, Colette', 'f', 'Chaumont, Haute-Marne, France', '1941']],
			[['BONDAR', 'Henri', 'g', 'Paris 18, Paris, France', '1936']],
			[['LOEW', 'Monique', 'f', 'Vilnius, Vilnius, Lituanie', '1933']],
			[],
			[['KELLER', 'Irene', 'f', 'Przemyśl, Podkarpackie, Pologne', '1929'], ['EISENBERG', 'Salomon', 'g', 'Paris 12, Paris, France', '1927'], ['LANDAU', 'Maurice', 'g', 'Paris 4, Paris, France', '1937']],
			[],
			[['KIERSZBAUM', 'Maurice', 'g', 'Michów, Lublin, Pologne', '1926']],
			[['RAB', 'Michel, Georges', 'g', 'Paris 19, Paris, France', '1935']],
			[],
			[],
			[],
			[['KIPER', 'Pierre', 'g', 'Będzin, Śląskie, Pologne', '1926']],
			[['SABAH', 'Tamar, Esther', 'f', 'La Roche-sur-Yon, Vendée, France', '1928']],
			[['BAER', 'Jacqueline, Gilberte, Alice', 'f', 'Chaumont, Haute-Marne, France', '1934'], ['METZLER', 'Gilbert, René', 'g', 'Sarreguemines, Moselle, France', '1933'], ['SCHAPIRO', 'Salomon', 'g', 'Paris 4, Paris, France', '1926']],
			[],
			[],
			[],
			[],
			[['BASSAN', 'Henri, Mossé, Haïm', 'g', "Saint-Brieuc, Côtes-d'Armor, France", '1938']],
			[]]];

function age(day1, month1, year1, day2, month2, year2){
	var Num_jour = [31,28,31,30,31,30,31,31,30,31,30,31];
	var age = "";
	var dif_year = Number.parseInt(year2) - Number.parseInt(year1);
	var dif_month = Number.parseInt(month2) - Number.parseInt(month1);
	var dif_day = Number.parseInt(day2) - Number.parseInt(day1);
	if (dif_day < 0){
		dif_month -= 1;
		dif_day += Num_jour[month1 - 1];
	}
	if (dif_month < 0){
		dif_year -= 1
		dif_month += 12
	}
	if (dif_year > 0){
		age = dif_year.toString() + ' an';
		if (dif_year > 1){
			age += "s";
		}
	}
	else{
		if (dif_month > 0){
			age = dif_month.toString() + ' mois';
		}
		else{
			age = dif_day.toString() + ' jour';
			if (dif_day > 1){
				age +="s";
			}
		}
	}
	return age;
}

function change(){
	var date_68 = "10/02/1944";
	var year_68 = Number.parseInt(date_68.split("/")[2]);
	var month_68 = Number.parseInt(date_68.split("/")[1]);
	var day_68 = Number.parseInt(date_68.split("/")[0]);
	var date = new Date();
	var year = 2023;//date.getFullYear();
	var month = 1;//date.getMonth() + 1;
	var day = 1;//date.getDate();
	var infos = data[month - 1][day - 1];
	if (infos.length > 0){
		var data_str = '<h1>Hommage aux enfants du convoi 68 déportés à Auschwitz</h1>';
	}
	else{
		var data_str = '';
	}
	var enfant;
	for (let num = 0; num < infos.length; num++){
		enfant = infos[num];
		var year_born = Number.parseInt(enfant[4]);
		data_str += "Il y a " + (year - year_born ).toString() + " ans, ";
		data_str += "jour pour jour naissait " 
		data_str += enfant[0] + " " + enfant[1];
		data_str += " à " + enfant[3].split(', ')[0] + " en " + enfant[3].split(', ')[2];
		data_str += ", déporté"
		if (enfant[2] == 'f'){
			data_str += "e";
		} 
		data_str += " à Auschwitz à l'âge de " + age(day, month, year_born, day_68, month_68, year_68);
		data_str += ".<br>Pensons à ";
		if (enfant[2] == 'g'){
			data_str += "lui";
		}
		else{
			if (enfant[2] == 'f'){
				data_str += "elle";
			}
		}
		data_str += ".<br><br>";
	}
	document.getElementById("current_date").innerHTML = data_str;
}
change();